name: Build and Push to ECR

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_DEV_REPOSITORY: ${{ vars.ECR_DEV_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region : ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_DEV_REPOSITORY
          docker build \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg GIT_SHA=${{ github.sha }} \
            -t $IMAGE_URI:${{ github.sha }} \
            -t $IMAGE_URI:latest \
            .

      - name: Push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_DEV_REPOSITORY
          docker push $IMAGE_URI:${{ github.sha }}
          docker push $IMAGE_URI:latest